enable deploy of a website for release pipelines

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -41,8 +41,16 @@ include:
     - echo "${WEBSITE_DEPLOY_SSH_PRIVATE_KEY_BASE64}" | base64 -d > ~/.ssh/id_ed25519
   script:
     # Determine which version gets deployed.
-    # FIXME: only latest is currently supported
-    - export WEBSITE_DEPLOY_VERSION="latest"
+    - |
+        if [[ "$CI_COMMIT_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?$ ]]; then
+            export WEBSITE_DEPLOY_VERSION="$CI_COMMIT_TAG"
+        elif [[ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH_TEST" ]]; then
+            export WEBSITE_DEPLOY_VERSION="latest"
+        else
+            echo "ERROR: could not determine deploy version."
+            exit 1
+        fi
+    - echo "Deploying version ${WEBSITE_DEPLOY_VERSION}"
     # Clone the documentation repository
     - git clone --filter=tree:0 --single-branch --branch="${WEBSITE_DEPLOY_TARGET_BRANCH}" "${WEBSITE_DEPLOY_TARGET_REPO}" "${WEBSITE_DEPLOY_CLONE_PATH}"
     # Introduce ourselves to Git
@@ -58,6 +66,8 @@ include:
     - rm -f ~/.ssh/id_ed25519
     - rm -rf "${WEBSITE_DEPLOY_CLONE_PATH}"
   rules:
+    - if: $CI_COMMIT_TAG =~ /^v[0-9]+.[0-9]+.[0-9]+(rc[0-9]+)?$/
+      when: on_success
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH_TEST
       when: on_success
     - when: never
